# Generated by Django 4.2.1 on 2023-06-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_postcode_shippingaddress_postcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Top', 'Top'), ('T-shirt', 'T-shirt'), ('Shirt', 'Shirt'), ('Pants', 'Pants'), ('Dress', 'Dress'), ('Jacket', 'Jacket')], max_length=200, null=True),
        ),
    ]
