# Generated by Django 4.2.1 on 2023-07-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_product_countinstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.CharField(choices=[('skincare', 'Skincare'), ('makeup', 'Makeup')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Cleanser', 'Cleanser'), ('Toner', 'Toner'), ('Moisturiser', 'Moisturiser'), ('Masks', 'Masks'), ('Face', 'Face'), ('Eyes', 'Eyes'), ('Lips', 'Lips')], max_length=200, null=True),
        ),
    ]
